[package]
name = "lru-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = {version = "0.5.2", default-features = false}

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"